modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "discsplus"
version = "${version}"
displayName = "DiscsPlus"
authors = "Atom596"
description = '''
Adds new Fanmade Discs into the game
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[4.1.32,)"
ordering = "AFTER"
side = "BOTH"